get-all-products=http://localhost:8080/getAllProducts
create-product=http://localhost:8080/addProduct
create-moc-product=http://localhost:8080/createTestProduct
get-product-by-barcode=http://localhost:8080/getProductByBarcode
find-cashier-by-id=http://localhost:8080/findCashierByID
find-cashier-by-employee-id=http://localhost:8080/findCashierByEmployeeID
find-sale-item-by-id=http://localhost:8080/getSaleRequestByID
get-all-cashiers=http://localhost:8080/getAllCashiers
create-cashier=http://localhost:8080/AddCashier
# Supplier endpoints
get-all-suppliers=http://localhost:8080/getAllSuppliers
create-supplier=http://localhost:8080/addSupplier

create-rewards-account=http://localhost:8080/createRewardsAccount
get-rewards-account-by-cell=http://localhost:8080/getRewardsAccountByCellphoneNumber
